/*
 * I8080
 * An implementation of the I8080 processor.
 *
 * Dr. Jeffrey Frey
 * University of Delaware
 *
 * Header that defines the Audio Processing Unit (APU) API.
 */
 
#ifndef __I8080APU_H__
#define __I8080APU_H__

#include "I8080Config.h"
#include "I8080Memory.h"

/**
 * Master control registers
 * The APU has a few global controls present in this register.
 *
 * By default the channels use 16-bit registers for frequency, duration, and envelope
 * timers.  Setting a \p is_8bit_* bit uses just the low-byte of these registers.
 *
 * For the envelope timers, the 8-bit value is multiplied by 2^8 to recover a
 * 16-bit value (with an exception for variable envelope where the 8-bit value is used as-is).
 *
 * For the duration timers, the 8-bit value is multiplied by 15 (the duration of a quarter
 * note).
 *
 * The frequency timer requires more precision, so the 8-bit value is an index that
 * references a frequency table that includes octaves 1 through 6 with interpolated
 * steps between the notes.  See the \ref I8080APU8BitFreqTimerMap documentation.
 *
 * The registers occupy 3 consecutive bytes.
 */
typedef struct __attribute__((packed)) {
#ifdef BITS_BIG_ENDIAN
    uint8_t                 is_8bit_frequency : 1;
    uint8_t                 is_8bit_duration : 1;
    uint8_t                 is_8bit_envelope : 1;
    uint8_t                 : 5;
#else
    uint8_t                 : 5;
    uint8_t                 is_8bit_envelope : 1;       /*!< envelope constant levels should be treated as 8-bit values * 2^8, or
                                                             an explicit 8-bit value for variable level */
    uint8_t                 is_8bit_duration : 1;       /*!< duration timers should be treated as 8-bit values * 2^8 */
    uint8_t                 is_8bit_frequency : 1;      /*!< frequency timers should be treated as 8-bit lookup indices rather than
                                                             16-bit values */
#endif
    uint8_t                 master_level_lo,
                            master_level_hi;            /*!< master volume level for the APU */
} I8080APUMasterRegisters_t;


/**
 * Pulse wave generator registers
 * Each pulse wave audio channel is controlled by a set of memory-mapped
 * registers.  All multi-byte values are ordered little-endian.
 *
 * The frequency is a 12.4 fixed-point value indicating the number of cycles
 * that fit within one 44100 Hz sampling period.  For example, an A4 note at 440 Hz
 * has a cycle count of 100.23, which in 12.4 fixed-point is 0x0644.  The lowest-representable
 * frequency, 0xFFFF, corresponds with 4095.93 cycles or 10.8 Hz.
 *
 * The registers occupy 9 consecutive bytes.
 *
 *     byte offset      description
 *     0                control bitmask; when this register is changed, the generator in question
 *                      is reset with the register values, so this register should be modified LAST
 *     1                the duty cycle profile index is present in the low nibble, the frequency shift
 *                      size in the high nibble (if sweep is enabled)
 *     2                if the envelope is constant the volume level in the range [0, 0x7FFF]; otherwise,
 *                      the number of 1/60 s periods between level changes
 *     4                the duration the waveform specified by the registers should be generated before
 *                      being silenced automatically; if zero, the channel must be muted manually
 *     6                the frequency timer for the waveform being generated by the channel, as the number of
 *                      44100 Hz cycles that comprise one wavelength in 12.4 fixed-point notation
 *     8                the number of frequencey cycles between changes in frequency during a sweep
 */
typedef struct __attribute__((packed)) {
#ifdef BITS_BIG_ENDIAN
    uint8_t             is_enabled : 1;
    uint8_t             is_envlp_const : 1;
    uint8_t             is_envlp_looped : 1;
    uint8_t             is_freq_swept : 1;
    uint8_t             : 4;
    
    uint8_t             freq_shift : 4;
    uint8_t             duty_cycle : 4;
#else
    uint8_t             : 4;
    uint8_t             is_freq_swept : 1;      /*!< 1 = the frequency changes over time */
    uint8_t             is_envlp_looped : 1;    /*!< 1 = for non-constant envelope, the level-cycling should
                                                     loop back to 0x7FFF when it hits zero */
    uint8_t             is_envlp_const : 1;     /*!< 1 = the envelope (volume) is constant */
    uint8_t             is_enabled : 1;         /*!< 1 = the channel is enabled, 0 = muted */
    
    uint8_t             duty_cycle : 4;         /*!< the duty cycle profile selector ∈ {0x0, 0xB} */
    uint8_t             freq_shift : 4;         /*!< if the frequency is swept, the right-shifts
                                                     of the current timer to yield the delta */
#endif
    uint8_t             envlp_level_lo,
                        envlp_level_hi;         /*!< if the envelope is constant, the volume level;
                                                     otherwise, the number of 1/60 s periods
                                                     between level changes */
    uint8_t             duration_lo,
                        duration_hi;            /*!< duration of the waveform in units of 1/60 s; if 0, the channel
                                                     must be silenced manually */
    uint8_t             freq_timer_lo,
                        freq_timer_hi;          /*!< the number of 44100 Hz cycles between peaks
                                                     in the waveform */
    uint8_t             freq_sweep_period;      /*!< the number of frequency cycles between frequency changes */
} I8080APUPulseChannelRegisters_t;


/**
 * Triangle wave generator registers
 * Each triangle wave audio channel is controlled by a set of memory-mapped
 * registers.  All multi-byte values are ordered little-endian.
 *
 * The frequency is a 12.4 fixed-point value indicating the number of cycles
 * that fit within one 44100 Hz sampling period.  For example, an A4 note at 440 Hz
 * has a cycle count of 100.23, which in 12.4 fixed-point is 0x0644.  The lowest-representable
 * frequency, 0xFFFF, corresponds with 4095.93 cycles or 10.8 Hz.
 *
 * The registers occupy 7 consecutive bytes.
 *
 *     byte offset      description
 *     0                control bitmask; when this register is changed, the generator in question
 *                      is reset with the register values, so this register should be modified LAST
 *     1                if the envelope is constant the volume level in the range [0, 0x7FFF]; otherwise,
 *                      the number of 1/60 s periods between level changes
 *     3                the duration the waveform specified by the registers should be generated before
 *                      being silenced automatically; if zero, the channel must be muted manually
 *     5                the frequency timer for the waveform being generated by the channel, as the number of
 *                      44100 Hz cycles that comprise one wavelength in 12.4 fixed-point notation
 */
typedef struct __attribute__((packed)) {
#ifdef BITS_BIG_ENDIAN
    uint8_t             is_enabled : 1;
    uint8_t             is_envlp_const : 1; 
    uint8_t             is_envlp_looped : 1;
    uint8_t             is_sawtooth : 1;
    uint8_t             : 4;
#else
    uint8_t             : 4;
    uint8_t             is_sawtooth : 1;        /*!< 1 = use a sawtooth waveform, 0 = use a triangle waveform */
    uint8_t             is_envlp_looped : 1;    /*!< 1 = for non-constant envelope, the level-cycling should
                                                     loop back to 0x7FFF when it hits zero */
    uint8_t             is_envlp_const : 1;     /*!< 1 = the envelope (volume) is constant */
    uint8_t             is_enabled : 1;         /*!< 1 = the channel is enabled, 0 = muted */
#endif
    uint8_t             envlp_level_lo,
                        envlp_level_hi;         /*!< if the envelope is constant, the volume level;
                                                     otherwise, the number of 1/60 s periods
                                                     between level changes */
    uint8_t             duration_lo,
                        duration_hi;            /*!< duration of the waveform in units of 1/60 s; if 0, the channel
                                                     must be silenced manually */
    uint8_t             freq_timer_lo,
                        freq_timer_hi;          /*!< the number of 44100 Hz cycles between peaks
                                                     in the waveform */
} I8080APUTriangleChannelRegisters_t;

/**
 * Noise generator registers
 * Each noise audio channel is controlled by a set of memory-mapped
 * registers.  All multi-byte values are ordered little-endian.
 *
 * The registers occupy 5 consecutive bytes.
 *
 *     byte offset      description
 *     0                control bitmask; when this register is changed, the generator in question
 *                      is reset with the register values, so this register should be modified LAST
 *     1                if the envelope is constant the volume level in the range [0, 0x7FFF]; otherwise,
 *                      the number of 1/60 s periods between level changes
 *     3                the duration the waveform specified by the registers should be generated before
 *                      being silenced automatically; if zero, the channel must be muted manually
 */
typedef struct __attribute__((packed)) {
#ifdef BITS_BIG_ENDIAN
    uint8_t             is_enabled : 1;
    uint8_t             is_envlp_const : 1; 
    uint8_t             is_envlp_looped : 1;
    uint8_t             is_short_loop : 1;
    uint8_t             period : 4;
#else
    uint8_t             period : 4;             /*!< which of the 16 cycling periods to use, with lower values having
                                                     higher frequencies */
    uint8_t             is_short_loop : 1;      /*!< 1 = use shortened RNG noise cycling, 0 = regular period */
    uint8_t             is_envlp_looped : 1;    /*!< 1 = for non-constant envelope, the level-cycling should
                                                     loop back to 0x7FFF when it hits zero */
    uint8_t             is_envlp_const : 1;     /*!< 1 = the envelope (volume) is constant */
    uint8_t             is_enabled : 1;         /*!< 1 = the channel is enabled, 0 = muted */
#endif
    uint8_t             envlp_level_lo,
                        envlp_level_hi;         /*!< if the envelope is constant, the volume level;
                                                     otherwise, the number of 1/60 s periods
                                                     between level changes */
    uint8_t             duration_lo,
                        duration_hi;            /*!< duration of the waveform in units of 1/60 s; if 0, the channel
                                                     must be silenced manually */
} I8080APUNoiseChannelRegisters_t;

/**
 * Delta PCM generator registers
 * Each delta PCM audio channel is controlled by a set of memory-mapped
 * registers.  All multi-byte values are ordered little-endian.
 *
 * The registers occupy 5 consecutive bytes.
 *
 *     byte offset      description
 *     0                control bitmask; when this register is changed, the generator in question
 *                      is reset with the register values, so this register should be modified LAST
 *     1                the address in system RAM at which the DPCM samples start
 *     3                the number of DPCM sample bytes in the sample
 */
typedef struct __attribute__((packed)) {
#ifdef BITS_BIG_ENDIAN
    uint8_t             is_enabled : 1;
    uint8_t             is_looped : 1;
    uint8_t             : 2;
    uint8_t             rate : 4;
#else
    uint8_t             rate : 4;               /*!< the sample rate as a divider of the 44100 Hz native rate; the divider is the
                                                     value of this field + 1, e.g. if rate=0, the divider d=1 and the sample rate
                                                     is 44100 Hz.  By comparison, for rate=6 the sample rate is 7350 Hz. */
    uint8_t             : 2;
    uint8_t             is_looped : 1;          /*!< 1 = replay the sample sequence indefinitely, 0 = play once */
    uint8_t             is_enabled : 1;         /*!< 1 = the channel is enabled, 0 = muted */
#endif
    uint8_t             address_lo,
                        address_hi;             /*!< address of the audio samples in emulator RAM */
    uint8_t             length_lo,
                        length_hi;              /*!< length (in bytes) of the audio samples */
} I8080APUDPCMChannelRegisters_t;

/**
 * APU channel registers
 * The APU implements a pair of pulse waveform generators; a pair of triangle/sawtooth
 * waveform generators; and a noise generator.  The channels are controlled via memory-mapped
 * registers ordered as in this data structure; each channel type has its own size and layout
 * relative to their base address dictated by position in the struct.
 */
typedef struct __attribute__((packed)) {
    I8080APUMasterRegisters_t           master;         /*!< 0x00: master registers (3 bytes) */
    I8080APUPulseChannelRegisters_t     pulse_0;        /*!< 0x03: pulse waveform channel 0 registers (9 bytes) */
    I8080APUPulseChannelRegisters_t     pulse_1;        /*!< 0x0C: pulse waveform channel 1 registers (9 bytes) */
    I8080APUTriangleChannelRegisters_t  triangle_0;     /*!< 0x15: triangle/sawtooth waveform channel 0 registers (7 bytes) */
    I8080APUTriangleChannelRegisters_t  triangle_1;     /*!< 0x1C: triangle/sawtooth waveform channel 1 registers (7 bytes) */
    I8080APUNoiseChannelRegisters_t     noise;          /*!< 0x23: noise generator ( 5 bytes ) */
    I8080APUDPCMChannelRegisters_t      dpcm;           /*!< 0x28: delta PCM (5 bytes) */
                                                        /*   0x2D */
} I8080APURegisters_t;

/**
 * APU register indices
 * This enumeration provides the APU 8-bit register number associated
 * with each named register.  The value also indicates the register's
 * offset from the base mapping address within the emulator.
 */
typedef enum {
    kI8080APURegisterIndexMasterState                   =  0,
    kI8080APURegisterIndexMasterEnvelopeLevelLo,
    kI8080APURegisterIndexMasterEnvelopeLevelHi,
    //
    kI8080APURegisterIndexPulse0State,
    kI8080APURegisterIndexPulse0DutyAndFreqShift,
    kI8080APURegisterIndexPulse0EnvelopeLevelLo,
    kI8080APURegisterIndexPulse0EnvelopeLevelHi,
    kI8080APURegisterIndexPulse0DurationLo,
    kI8080APURegisterIndexPulse0DurationHi,
    kI8080APURegisterIndexPulse0FrequencyTimerLo,
    kI8080APURegisterIndexPulse0FrequencyTimerHi,
    kI8080APURegisterIndexPulse0FreqSweepPeriod,
    //
    kI8080APURegisterIndexPulse1State,
    kI8080APURegisterIndexPulse1DutyAndFreqShift,
    kI8080APURegisterIndexPulse1EnvelopeLevelLo,
    kI8080APURegisterIndexPulse1EnvelopeLevelHi,
    kI8080APURegisterIndexPulse1DurationLo,
    kI8080APURegisterIndexPulse1DurationHi,
    kI8080APURegisterIndexPulse1FrequencyTimerLo,
    kI8080APURegisterIndexPulse1FrequencyTimerHi,
    kI8080APURegisterIndexPulse1FreqSweepPeriod,
    //
    kI8080APURegisterIndexTriangle0State,
    kI8080APURegisterIndexTriangle0EnvelopeLevelLo,
    kI8080APURegisterIndexTriangle0EnvelopeLevelHi,
    kI8080APURegisterIndexTriangle0DurationLo,
    kI8080APURegisterIndexTriangle0DurationHi,
    kI8080APURegisterIndexTriangle0FrequencyTimerLo,
    kI8080APURegisterIndexTriangle0FrequencyTimerHi,
    //
    kI8080APURegisterIndexTriangle1State,
    kI8080APURegisterIndexTriangle1EnvelopeLevelLo,
    kI8080APURegisterIndexTriangle1EnvelopeLevelHi,
    kI8080APURegisterIndexTriangle1DurationLo,
    kI8080APURegisterIndexTriangle1DurationHi,
    kI8080APURegisterIndexTriangle1FrequencyTimerLo,
    kI8080APURegisterIndexTriangle1FrequencyTimerHi,
    //
    kI8080APURegisterIndexNoiseState,
    kI8080APURegisterIndexNoiseEnvelopeLevelLo,
    kI8080APURegisterIndexNoiseEnvelopeLevelHi,
    kI8080APURegisterIndexNoiseDurationLo,
    kI8080APURegisterIndexNoiseDurationHi,
    //
    kI8080APURegisterIndexDPCMState,
    kI8080APURegisterIndexDPCMAddressLo,
    kI8080APURegisterIndexDPCMAddressHi,
    kI8080APURegisterIndexDPCMLengthLo,
    kI8080APURegisterIndexDPCMLengthHi,
    //
    kI8080APURegisterIndexMiscSpeakerStrobe,
    //
    kI8080APURegisterIndexMax
} I8080APURegisterIndex_t;

/**
 * Relative address of APU master registers
 * The APU master registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetMasterRegisters;

/**
 * Relative address of APU pulse channel 0 registers
 * The APU pulse channel 0 registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetPulse0Registers;

/**
 * Relative address of APU pulse channel 1 registers
 * The APU pulse channel 1 registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetPulse1Registers;

/**
 * Relative address of APU triangle channel 0 registers
 * The APU triangle channel 0 registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetTriangle0Registers;

/**
 * Relative address of APU triangle channel 1 registers
 * The APU triangle channel 1 registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetTriangle1Registers;

/**
 * Relative address of APU noise channel registers
 * The APU noise channel registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetNoiseRegisters;

/**
 * Relative address of APU DPCM channel registers
 * The APU DPCM channel registers can be found at this address relative to the
 * mapping base address.
 */
extern const I8080Addr_t I8080APUAddrOffsetDPCMRegisters;

/**
 * Type of a pointer to a APU mapper context
 */
typedef const void * I8080APUMapperContextPtr;

I8080APUMapperContextPtr I8080APUMapperContextCreate();

uint8_t I8080APUMapperContextGetRegister(I8080APUMapperContextPtr apu, I8080APURegisterIndex_t rgstr_idx);
void I8080APUMapperContextSetRegister(I8080APUMapperContextPtr apu, I8080APURegisterIndex_t rgstr_idx, uint8_t byte);

/**
 * APU callbacks
 * Address of the callbacks that implement the \ref I8080APUMapperContext_t
 * operations.
 */
extern const I8080MemMapperCallbacks *I8080APUMapperCallbacks;

/**
 * Length of the address space occupied by the APU
 * Since this is a fixed constant, it's exposed as a fixed constant.
 */
extern const I8080Addr_t I8080APUMapperAddressRangeLength;

#endif /* __I8080APU_H__ */
