;
; Color indices:
;
COLOR_BLACK         equ     00h
COLOR_DK_GRAY       equ     01h
COLOR_DK_BLUE       equ     02h
COLOR_LT_BLUE       equ     03h
COLOR_DK_GREEN      equ     04h
COLOR_LT_GREEN      equ     05h
COLOR_DK_TEAL       equ     06h
COLOR_LT_TEAL       equ     07h
COLOR_DK_RED        equ     08h
COLOR_LT_RED        equ     09h
COLOR_DK_PURPLE     equ     0Ah
COLOR_LT_PURPLE     equ     0Bh
COLOR_BROWN         equ     0Ch
COLOR_YELLOW        equ     0Dh
COLOR_LT_GRAY       equ     0Eh
COLOR_WHITE         equ     0Fh
